openedx/frontend-app-payment

package-lock.json
src/payment/PaymentPage.jsx
src/payment/PaymentPage.test.jsx
src/payment/__mocks__/loadedBasket.mockStore.js
src/payment/__mocks__/loadedBasketWithNoTotals.mockStore.js
src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/_style.scss
src/payment/components/BasketSummary.jsx
src/payment/components/OrderDetails.jsx
src/payment/data/__mocks__/getBasket.json
src/payment/data/reducers.js
src/payment/data/selectors.js
src/payment/data/service.js

feat: add order summary and order details

---

src/payment/BasketSummary.jsx
src/payment/PaymentPage.jsx
src/payment/PaymentPage.test.jsx
src/payment/ProductLineItem.jsx
src/payment/ProductLineItems.jsx
src/payment/__mocks__/loadedBasket.mockStore.js
src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/data/selectors.js
src/payment/data/service.js

WIP UI Product Details section of payment page. Feedback appreciated. 
FYI @edx/arch-squad

UI: Product Details

---

package-lock.json
package.json
src/payment/BasketSummary.jsx
src/payment/CardHolderInformation.jsx
src/payment/OrderDetails.jsx
src/payment/PaymentForm.jsx
src/payment/PaymentPage.jsx
src/payment/ProductLineItem.jsx
src/payment/ProductLineItems.jsx
src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/_style.scss
src/payment/coupon/CouponForm.jsx
src/payment/coupon/__snapshots__/CouponForm.test.jsx.snap

fix: layout improvements

---

docs/decisions/0003-saga-service-testing.rst

ADR on saga/service testing.

---

src/payment/data/sagas.js

ARCH-853: handle no voucher case

---

package-lock.json
src/payment/data/service.js

Any API response containing a `redirect` value will set `window.location.href` to that value.

feat: redirect users when 200 response has redirect value

---

src/payment/PaymentPage.jsx
src/payment/PaymentPage.test.jsx
src/payment/PlaceOrderButton.jsx
src/payment/ProductLineItem.jsx
src/payment/__mocks__/defaultState.mockStore.js
src/payment/__mocks__/loadedBasket.mockStore.js
src/payment/__mocks__/loadedEmptyBasket.mockStore.js
src/payment/__mocks__/loadedFreeBasket.mockStore.js
src/payment/__mocks__/loading.mockStore.js
src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/coupon/data/sagas.js
src/payment/coupon/data/sagas.test.js
src/payment/data/selectors.js
webpack/webpack.dev.config.js

If the `is_free_basket` boolean is true, it will render just a "Place Order" button that redirects to a free checkout link. When the 100% coupon is removed, the Payment Form is rendered.

refactor: free checkout

---

package-lock.json
src/common/components/FormInput.jsx
src/common/components/FormSelect.jsx
src/environment.js
src/payment/CardDetails.jsx
src/payment/CardDetails.test.jsx
src/payment/CardHolderInformation.jsx
src/payment/PaymentForm.jsx
src/payment/StateProvinceFormInput.jsx
src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/data/__mocks__/getBasket.json
src/payment/data/actions.js
src/payment/data/reducers.js
src/payment/data/sagas.js
src/payment/data/service.js
webpack/webpack.dev-stage.config.js
webpack/webpack.dev.config.js
webpack/webpack.prod.config.js

**This enables Cybersource payment submission. There will be refactoring after this is merged to enable PayPal and ApplePay.**
Overview of how payment submission works for Cybersource:
1. User clicks Place Order button.
2. `handleSubmitPayment` orchestrates three network interactions:
1. SDN check API request to ecommerce service
2. Cybersource submit  API request to ecommerce service (this freezes the basket in the ecommerce service and returns a dict of keys/values that need to get POST'ed directly to the Cybersource API.)
3. Form POST submission to Cybersource endpoint.
3. The form submission to Cybersource redirects to the ecommerce service-rendered receipt page.
`<input type="hidden" />` elements are used to submit the necessary values to Cybersource for payment authorization. The …

Implement payment submission.

---

src/common/components/FormInput.jsx
src/common/components/FormSelect.jsx
src/payment/CardDetails.jsx
src/payment/CardHolderInformation.jsx
src/payment/PaymentPage.jsx
src/payment/ProductLineItem.jsx
src/payment/StateProvinceFormInput.jsx
src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/_style.scss

Waiting on review with Jeff. 
[ARCH-963](https://openedx.atlassian.net/browse/ARCH-963).

refactor: a11y

---

babel.config.js
package-lock.json
package.json
src/index.jsx

It’ll technically go out to prod that way, but won’t ever be downloaded by the client.

Import react axe dynamically

---

src/common/utils.js
src/common/utils.test.js
src/payment/PlaceOrderButton.test.jsx

Tests for generateAndSubmitform and the PlaceOrderButton, bringing both to 100% coverage

Tests backfill - first pass

---

src/payment/coupon/CouponForm.jsx
src/payment/coupon/CouponForm.test.jsx

Added ecommerce event for coupons `edx.bi.ecommerce.basket.voucher_applied`.
[ARCH-941](https://openedx.atlassian.net/browse/ARCH-941).

fix: add coupon sendTrackEvent

---

src/payment/coupon/CouponForm.test.jsx
src/payment/coupon/data/sagas.js
src/payment/coupon/data/sagas.test.js
src/payment/coupon/data/service.js
src/payment/data/sagas.js
src/payment/data/service.js
src/payment/utils/handleBasketApiError.js

Also pass through get parameter to first getBasket request.
This will need a refactor in the future.

feat: update basket data on all requests

---

src/payment/CardDetails.jsx
src/payment/PaymentForm.jsx
src/payment/PaymentMethodSelect.jsx
src/payment/PaymentPage.jsx
src/payment/SummarySkeleton.jsx
src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/_style.scss
src/payment/apple-pay/ApplePayButton.jsx
src/payment/apple-pay/ApplePayButtonContainer.jsx
src/payment/apple-pay/__snapshots__/ApplePayButton.test.jsx.snap
src/payment/data/reducers.js
src/payment/order-details/data/selectors.js
src/payment/paypal/PayPalButton.jsx

feat: add a loading skeleton for cart section

---

src/payment/LocalizedPrice.jsx

fix(prices): localized currencies should not show decimal places

---

src/payment/data/service.js

We lost configuring the apple pay service somewhere along the way.

fix: re-add configuring apple pay service

---

public/index.html
webpack/webpack.common.config.js
webpack/webpack.dev-stage.config.js
webpack/webpack.dev.config.js
webpack/webpack.prod.config.js

Speed up requests by pre-connecting to known required domains.

feat: pre-connect to required domain origins

---

package-lock.json
package.json
src/index.scss

feat: remove webfont

---

src/payment/coupon/CouponForm.jsx

This is only a temporary fix, since we have a PR coming in that will refactor this code and fix it for real.

fix(coupon): deal with non-string value

---

public/index.html

Add a spinner for before React DOM mounts the app

fix: add a spinner on initial html render

---

src/payment/PaymentForm.jsx
src/payment/PaymentMethodSelect.jsx
src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/_style.scss
src/payment/paypal/PayPalButton.jsx

Partially addresses ARCH-971
PayPal
Submit

ARCH-971: Add submitting feedback states to buttons

---

package-lock.json
package.json
src/index.jsx

ARCH-1066: Sometimes we fail to get an access token. Handle this case by showing our error page and add logging for future investigation.

fix: handle failure to get access token

---

src/payment/PaymentForm.jsx
src/payment/PaymentMethodSelect.jsx
src/payment/PaymentPage.jsx
src/payment/UpdateQuantityForm.jsx
src/payment/__mocks__/customAlertMessages.mockStore.js
src/payment/__mocks__/defaultState.mockStore.js
src/payment/__mocks__/loadedBasket.mockStore.js
src/payment/__mocks__/loadedBasketWithNoTotals.mockStore.js
src/payment/__mocks__/loadedEmptyBasket.mockStore.js
src/payment/__mocks__/loadedFreeBasket.mockStore.js
src/payment/__mocks__/loading.mockStore.js
src/payment/data/reducers.js
src/payment/data/selectors.js
src/payment/order-summary/CouponForm.jsx

ARCH-1068: During any api request to basket endpoints disable any buttons that would modify the basket in any way. This ensures the frontend app will contain basket data that matches the server's

fix: disable buttons while basket is processing

---

package-lock.json
package.json

The most recent version includes the git repo which is causing build issues.

fix: pin i18n-iso-languages package

---

src/index.jsx

**NOTE**: This could use an extra-thoughtful review, as there are currently no tests for this part of our code (and writing them would be difficult).  
Do this by wrapping app initialization in a try/catch and going to error page from there.  Fixes this issue and also catches any other weird errors that may happen.

Throw an error if application state is empty object.

---

src/common/components/ErrorPage.jsx
src/payment/UpdateQuantityForm.jsx

Fix the weird error message, and make the max number of coupons a variable (otherwise, changing this number would require re-translating the string for all languages).

two message updates

---

src/payment/AlertCodeMessages.jsx
src/payment/PaymentPage.jsx

fix: add info message for quantity updated

---

README.rst

Still working on the README, but figure I'll check things in as I go.

Adding Getting Started info to README

---

src/payment/PaymentPage.jsx
src/payment/PaymentPage.test.jsx
src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/data/selectors.js

I'd like to deploy this to stage so we can test it more fully - I wasn't able to get an actual redirect back from the server while developing.

If the basket response indiciates we should redirect, show a spinner.

---

README.rst
src/payment/README.rst

"What are all these directories?"
"Read this!"

Preliminary code structure docs

---

src/payment/CardHolderInformation.messages.jsx
src/payment/StateProvinceFormInput.messages.jsx
src/payment/__snapshots__/PaymentPage.test.jsx.snap

Cease to use angle brackets in messages.

---

src/payment/apple-pay/service.js
src/payment/apple-pay/service.test.js

Disable back button from receipt page after going through payment flow
[REV-690](https://openedx.atlassian.net/browse/REV-690)

Pass query param to disable back button

---

src/payment/apple-pay/service.js
src/payment/apple-pay/service.test.js

refactor: remove console logs from apple pay

---

src/payment/PaymentMethodSelect.jsx
src/payment/PaymentPage.jsx
src/payment/PaymentPage.test.jsx
src/payment/UpdateQuantityForm.jsx
src/payment/__mocks__/loadedRedirect.mockStore.js
src/payment/apple-pay/ApplePayButton.test.jsx
src/payment/apple-pay/ApplePayButtonContainer.jsx
src/payment/apple-pay/ApplePayButtonContainer.test.jsx
src/payment/apple-pay/service.test.js
src/payment/data/actions.js
src/payment/data/reducers.js
src/payment/data/selectors.js

And re-enable it once done (cancel, fail, success)

Disable the Apple Pay button after initial click.

---

src/payment/CardDetails.jsx
src/payment/CardHolderInformation.jsx

Added autocomplete attributes to forms. 
[ARCH-1112](https://openedx.atlassian.net/browse/ARCH-1112).

fix: form autocomplete

---

src/feedback/data/redux.test.js
src/feedback/data/sagas.test.js

It was just missing a few tests / edge cases.

Getting feedback module to 100% coverage.

---

src/payment/payment-methods/cybersource/service.test.js

Check for errors thrown on SDN failure

tests: add cybersource test

---

src/payment/cart/CouponForm.test.jsx
src/payment/cart/__snapshots__/CouponForm.test.jsx.snap

tests: add coverage for coupon form

---

src/payment/payment-methods/apple-pay/service.js
src/payment/payment-methods/apple-pay/service.test.js
src/payment/payment-methods/cybersource/service.js
src/payment/payment-methods/cybersource/service.test.js
src/payment/payment-methods/paypal/service.js
src/payment/payment-methods/paypal/service.test.js

fix: add more error logging for checkout services

---

src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/checkout/payment-form/PaymentForm.jsx

Greatly simply the e2e tests by being able to refer to the place
order button directly.
ARCH-998

add place order button id for e2e.

---

src/payment/data/actions.js
src/payment/data/reducers.js
src/payment/data/redux.test.js
src/payment/data/sagas.js
src/payment/data/sagas.test.js

Rework processing into a single action so we can avoid reintroducing bugs regarding toggling the processing state moving forward

fix: add basket processing specific action

---

src/payment/cart/Offers.jsx
src/payment/data/sagas.js
src/payment/data/sagas.test.js

Also fixed a props "isRequired" issue that we missed earlier.

Bump REVEM-379 test coverage up up up.

---

README.rst
package-lock.json
src/payment/cart/Offers.jsx
src/payment/cart/Offers.test.jsx
src/payment/cart/__snapshots__/Offers.test.jsx.snap
src/payment/data/sagas.js
src/payment/data/sagas.test.js
src/payment/data/service.js

I still need to write tests for this, but I wanted to validate my approach at a high level in the meantime

add first purchase discount to mfe

---

package-lock.json
package.json
src/payment/AlertCodeMessages.jsx
src/payment/AlertCodeMessages.test.jsx
src/payment/PaymentPage.jsx
src/payment/__snapshots__/AlertCodeMessages.test.jsx.snap
src/payment/cart/Offers.jsx

[REV-940](https://openedx.atlassian.net/browse/REV-940) 
- Updated MFE to display the message for TransactionDeclined (as opposed to receiving it from Ecommerce)

REV-940: transaction declined message error

---

webpack/webpack.dev.config.js

[REV-947](https://openedx.atlassian.net/browse/REV-947).

updated cybersource redirect url 

---

package-lock.json
package.json
src/index.jsx

See https://github.com/edx/frontend-auth/releases/tag/v6.0.2
ARCH-948

ARCH-948: upgrade frontend-auth to 6.0.2

---

.eslintrc
package-lock.json
package.json
src/index.jsx

ARCH-948: upgrade frontend-auth to 7.0.0

---

src/index.jsx

rethrow errors from ensureAuthenticatedUser

---

src/payment/data/sagas.js
src/payment/data/sagas.test.js

excluding non-seat products like enrollment codes for bulk purchase from first purchase discount

exclude bulk purchase from discount

---

package-lock.json

[REV-951](https://openedx.atlassian.net/browse/REV-951). 
Server vulnerability fix for original merged PR https://github.com/edx/frontend-app-payment/pull/264.

fix: npm audit (military states)

---

src/payment/cart/Cart.jsx
src/payment/cart/Offers.jsx

https://openedx.atlassian.net/browse/REV-979
before:
after:

don't show first purchase discount message for bundles

---

package-lock.json
src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/checkout/payment-form/CardHolderInformation.jsx
src/payment/checkout/payment-form/CardHolderInformation.test.jsx
src/payment/checkout/payment-form/PaymentForm.jsx
src/payment/payment-methods/cybersource/service.js

Same change as before, now on the MFE:

Add purchased_for_organization basket attribute to bulk purchase form

---

src/common/components/FormInput.jsx
src/payment/__snapshots__/PaymentPage.test.jsx.snap

Set default to false as that seems reasonable

Fix propType warning for disabled on formInput

---

jest.config.js
src/index.jsx
src/payment/PaymentPage.test.jsx
src/payment/cart/Cart.test.jsx
src/payment/cart/OrderSummary.jsx
src/payment/checkout/payment-form/CardHolderInformation.test.jsx
src/payment/checkout/payment-form/PaymentForm.jsx
src/payment/checkout/payment-form/PaymentForm.test.jsx
src/payment/data/utils.js
src/payment/index.js
src/payment/performanceEventing.js
src/payment/speedcurve.js

Segment events will also likely be useful since we'll probably add
events to the backend as well.

Add segment events to accompany speedcurve events

---

src/data/configureStore.js
src/payment/checkout/payment-form/CardHolderInformation.jsx
src/payment/checkout/payment-form/PaymentForm.jsx

Fixes issue where state/province was still required for US/Canada

Fix issue with state required for US

---

src/payment/checkout/Checkout.jsx
src/payment/checkout/payment-form/CardDetails.jsx
src/payment/checkout/payment-form/CardHolderInformation.jsx

Update formatting for experiment

---

public/index.html

Reverts edx/frontend-app-payment#307
temporarily reverting

Revert "preload optimizely snippet from cloudflare worker"

---

package-lock.json
package.json
webpack.dev-stage.config.js

Upgrade frontend-build which now includes a dev-stage webpack config to build from. `npm run start:stage` should now work properly.

build: fix stage-dev server

---

package-lock.json
src/payment/PaymentPage.jsx
src/payment/cart/Cart.jsx
src/payment/cart/ProductLineItem.jsx
src/payment/index.scss

[REV-1013](https://openedx.atlassian.net/browse/REV-1013).
Adding Optimizely Experiment to display:
- Number enrolled of a course. Excludes courses with < 5000 enrolled. 
Note: enrollmentCountData content will be added in Optimizely.

Add num enrolled experiment

---

src/payment/cart/ProductLineItem.jsx

[REV-1013](https://openedx.atlassian.net/browse/REV-1013). 
Removing i18n as temporary fix to get the experiment live.

fix: Remove translation to num enrolled

---

src/payment/PaymentPage.jsx
src/payment/cart/Cart.jsx
src/payment/cart/order-details/OrderDetails.jsx
src/payment/checkout/Checkout.jsx
src/payment/checkout/payment-form/PaymentForm.jsx

[REV-1045] Decrease perception of loading time on left side

---

package-lock.json
package.json
src/payment/PaymentPage.jsx
src/payment/cart/Cart.jsx
src/payment/index.scss

[REV-1048](https://openedx.atlassian.net/browse/REV-1048).

add isPriceMessageExperiment to Cart

---

public/index.html
src/payment/__snapshots__/PaymentPage.test.jsx.snap

since we're not using optimizely web on frontend-app-payment right now, hoping to try out whether edge will work and if so, see what performance footprint it has

temporarily switch optimizely web for edge

---

package-lock.json
package.json
src/payment/PaymentPage.jsx
src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/cart/Cart.jsx
src/payment/cart/__snapshots__/Cart.test.jsx.snap

[REV-1062](https://openedx.atlassian.net/browse/REV-1062).
- Experiment to add a fair price messaging to Payment MFE.

Add transparent pricing experiment

---

package-lock.json
package.json
public/REV1074/test.html
public/static-checkout/js/scripts.js
webpack.prod.config.js

The routing code in ecommerce was assuming a certain structure. The structure was different here so I was making changes to fix that.
I also changed what we are sending to cybersource to fix some errors I ran into when trying to check out.
Paypal checkout still didn't work for me but I'm not sure if it works locally, was hoping to test on stage or eventually prod

Ensure we are able to checkout with cybersource and load the paypal payment page

---

src/payment/cart/OrderSummary.jsx
src/payment/index.js

Use try-catch to be completely robust against browsers that don't support performance or do it wrong

Use try-catch to be robust against uneven browser support

---

src/feedback/data/sagas.js
src/feedback/data/sagas.test.js
src/payment/data/sagas.js

this will handle the code that should be sent by https://github.com/edx/ecommerce/pull/2932

[REV-1170] emit error message when submitting an invalid code from the static page

---

package-lock.json

[REV-1256](https://openedx.atlassian.net/browse/REV-1256).
Updated packages:
lodash: 4.17.15 to 4.17.19. 
http-proxy: 1.18.0 to 1.18.1. 
eventemitter3: 4.0.0 to 4.0.4

Upgrade packages including lodash

---

src/payment/data/sagas.js

Hacky, but at least alerts the user to the impending timeout.

MVP: Post messages alerting user to the time limit

---

src/payment/checkout/payment-form/PaymentForm.jsx
src/payment/checkout/payment-form/contexts.js
src/payment/checkout/payment-form/flex-microform/FlexMicroformField.jsx

Reverts edx/frontend-app-payment#412

Revert "Focus on the microform field if an error occurs"

---

src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/checkout/payment-form/CardDetails.jsx
src/payment/checkout/payment-form/CardHolderInformation.jsx
src/payment/checkout/payment-form/StateProvinceFormInput.jsx
src/payment/checkout/payment-form/flex-microform/CreditCardNumberField.jsx
src/payment/checkout/payment-form/flex-microform/CreditCardVerificationNumberField.jsx
src/payment/checkout/payment-form/flex-microform/FlexMicroformField.jsx

Should fix:
1. Credit card icons
2. iframed fields not being disabled when the user clicks "Place Order"
3. Lock icon missing

Fix UI bugs related to Flex Microform

---

audit-ci.json
src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/cart/OrderSummary.jsx
src/payment/checkout/Checkout.jsx
src/payment/checkout/Checkout.test.jsx
src/payment/checkout/payment-form/CardDetails.jsx
src/payment/checkout/payment-form/PaymentForm.jsx
src/payment/data/__snapshots__/redux.test.js.snap
src/payment/data/reducers.js
src/payment/data/selectors.js

Reverts edx/frontend-app-payment#434

Revert "Default to microform"

---

src/payment/checkout/payment-form/PaymentForm.jsx
src/payment/checkout/payment-form/flex-microform/FlexMicroformField.jsx

If the microform doesn't initialize for some reason, paypal should still work and place order button should not enable

PCI-130 Payment page should gracefully handle uninitialized microform

---

public/index.html
webpack.dev-stage.config.js
webpack.dev.config.js
webpack.prod.config.js

Reverts edx/frontend-app-payment#400
https://openedx.atlassian.net/browse/REV-1532
Add optimizely back to checkout page now that the PCI work is sufficiently complete

Revert "[REV-1258] Remove optimizely from checkout page for PCI compliance reasons"

---

public/index.html

Reverts edx/frontend-app-payment#442

Revert "Use 0.11.1 version of the flex-microform javascript so that incorrect…"

---

src/payment/PaymentPage.jsx
src/payment/cart/Cart.jsx
src/payment/cart/CouponForm.jsx
src/payment/cart/OrderSummary.jsx
src/payment/checkout/Checkout.jsx
src/payment/checkout/Checkout.test.jsx
src/payment/checkout/payment-form/CardDetails.jsx
src/payment/checkout/payment-form/CardDetails.test.jsx
src/payment/checkout/payment-form/CardHolderInformation.jsx
src/payment/checkout/payment-form/PaymentForm.jsx
src/payment/checkout/payment-form/PaymentForm.test.jsx
src/payment/data/reducers.js
src/payment/data/sagas.js
src/payment/data/selectors.js
src/payment/payment-methods/cybersource/index.js
src/payment/payment-methods/cybersource/service.js
src/payment/payment-methods/cybersource/service.test.js

Delete the old payment form and other unused code
Note: there are still some tests that will need to be updated (or written at all), those changes will be in another PR.

PCI-140: prune old payment form

---

package-lock.json
package.json
src/payment/checkout/Checkout.test.jsx
src/payment/checkout/payment-form/CardDetails.test.jsx
src/payment/data/sagas.test.js
src/payment/payment-methods/cybersource/service.js
src/payment/payment-methods/cybersource/service.test.js

Updated tests for the new microform, added a couple; there is still much that could be tested, but don't want to get mired for too long.

PCI-137 add frontend tests

---

package-lock.json
package.json
src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/cart/CouponForm.jsx
src/payment/cart/UpdateQuantityForm.jsx
src/payment/cart/__snapshots__/Cart.test.jsx.snap
src/payment/cart/__snapshots__/CouponForm.test.jsx.snap
src/payment/checkout/payment-form/PaymentForm.jsx

[REV-1604](https://openedx.atlassian.net/browse/REV-1604) rebrand work for Payment MFE, starting with updating Paragon from version 7.2.1 to 12.3.0 (some breaking changes updated for Button and StatefulButton). 
Actual branding styles changes will come in a separate PR.

Update Paragon for rebranding 

---

src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/checkout/payment-form/CardHolderInformation.jsx
src/payment/checkout/payment-form/FormSelect.jsx
src/payment/checkout/payment-form/StateProvinceFormInput.jsx
src/payment/index.scss
webpack.dev-stage.config.js
webpack.dev.config.js
webpack.prod.config.js

[REV-1604](https://openedx.atlassian.net/browse/REV-1604). 
Misc updates for rebrand styles for checkout page: 
1) Close the loop on adding a favicon to Payment MFE 
2) Update payment method buttons to reflect new styles. 
3) Missing ; in CSS flex-microform
4) Fix issue with double dropdown arrow on select fields in Safari/Firefox in the component
Payment methods buttons should have no border-radius:

Fix rebranding misc updates

---

package-lock.json
package.json

Dependency high security vulnerability fixed by upgrading `frontend-build`. 
Path: @edx/frontend-build > resolve-url-loader > adjust-sourcemap-loader > object-path

Upgrade frontend-build to 5.6.8

---

renovate.json

This will auto update renovate PRs and make renovate run on weekends.

Auto rebase renovate PRs and only create PRs on weekends

---

README.rst

The README contained out-of-date setup instructions; updated them ahead of the Lilac release

doc: updated README now that f-a-payment is default in devstack

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md

Added CODEOWNERS file to require @edx/revenue-squad review during merge-freeze

Added CODEOWNERS and announcement of merge-freeze

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md

Reverts edx/frontend-app-payment#480

Revert "Added CODEOWNERS and announcement of merge-freeze"

---

package-lock.json
package.json

The payment MFE keeps crashing locally with the symptom described and fixed in this PR: 
https://github.com/edx/frontend-build/pull/172
This PR is to update our frontend-build version to get the fix for this issue.

chore: upgrade frontend-build version

---

package-lock.json
package.json

Updated `frontend-build` for some high-severity security issues; for some reason I still had to run `npm audit fix` in this repo as well.
Hoping this can fix the [#85 heisenbug](https://github.com/openedx/frontend-wg/issues/85)
See [[REV-2657] (After fix to frontend-build) Finish frontend-app-payment deploy in progress! - JIRA](https://openedx.atlassian.net/browse/REV-2657)
I've only seen the above bug that is blocking the pipeline in the Stage build, so that's where I'll test this.

build: updated f-a-build and ran npm audit fix

---

.github/workflows/ci.yml
package-lock.json
package.json

Project Zebra set up for the MFE.
**This PR:**
- Install Stripe package
- Add `project-zebra` as one of the branches for running CI

feat: Install Stripe package and add project-zebra branch to run CI

---

docs/how_tos/feature_toggle.rst

Add a HOWTO guide that walks through how to use waffle flags in frontend-app-payment, and how it was used for the rollout of the updated Stripe Payment Intents payment processor in frontend-app-payment and ecommerce.
* Jira: [REV-3150](https://2u-internal.atlassian.net/browse/REV-3150) Update the decisions docs with Stripe work for payment MFE and ecommerce.

docs: add feature_toggle HOWTO

---

.github/workflows/ci.yml
.github/workflows/lockfileversion-check.yml

[REV-3283](https://2u-internal.atlassian.net/browse/REV-3283)

build: add 2u/project-theseus branch to run ci

---

package-lock.json
package.json

-  Updated frontend-build version to fix semver-regex vulnerability. 
ticket [REV-2810](https://2u-internal.atlassian.net/browse/REV-2810)

Updated frontend build version to fix semver regex vulnerability

---

docs/how_tos/feature_toggle.rst

- Updates to Feature Toggle documentation for Environmental Flags
- Updating code pointers to show how the code was broken out
This is part of THES-242.

docs: Updates to Feature Toggle documentation for Environmental Flags

---

public/index.html

temp: add maintenance page for mysql8 upgrade

---

public/index.html

This reverts commit ef9ea1b7525d9cba7c06a65254cdb4ba5bd2c1ac.

Revert "temp: add maintenance page for mysql8 upgrade (#807)"

---

audit-ci.json
package-lock.json
package.json

This PR resolves the `PUBLIC_PATH` configuration issue by upgrading frontend-platform from `v5.0.0` to `v5.5.4`.

chore: bump frontend-platform

---

package-lock.json
package.json

* chore: bump frontend-platform
* fix: security vulnerabilities

chore: bump frontend-platform (#815)

---

audit-ci.json
package-lock.json

fix: fixed and whitelisted vulnerabilities

---

.github/workflows/lockfileversion-check.yml
package-lock.json

Renamed `lockfileversion-check-v3` to `lockfile-check` in lockfile version file.
[Prototype a way to review NPM lockfiles in PRs](https://github.com/edx/edx-arch-experiments/issues/355)

refactor: updated lock file version check to use new workflow

---

audit-ci.json
public/index.html

Reverts openedx/frontend-app-payment#857

Revert temp: add maintenance page for Django Oscar 3.1 Upgrade
