src/payment/PaymentPage.jsx
src/payment/__mocks__/getBasket.json
src/payment/actions.js
src/payment/reducer.js
src/payment/saga.js
src/payment/service.js

populate page with mock data

---

package-lock.json
package.json
src/index.jsx

Adding react-axe.  It logs accessibility errors to the console in dev (not production) mode.
Yes, those are real errors we have right now.

Add react-axe to project.

---

src/payment/CardDetails.jsx
src/payment/CardHolderInformation.jsx
src/payment/PaymentPage.jsx
src/payment/ProductLineItem.jsx
src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/_style.scss

fix: minor typography updates

---

src/payment/coupon/data/sagas.js
src/payment/coupon/data/sagas.test.js
src/payment/coupon/data/service.js
src/payment/data/service.js

ARCH-853: refactor bff api and implement more of coupons

---

package-lock.json
package.json
src/payment/CardDetails.jsx
src/payment/CardDetails.test.jsx
src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/_style.scss

Add credit card type detection.

---

src/common/components/FormInput.jsx
src/common/components/FormSelect.jsx
src/payment/CardDetails.jsx
src/payment/CardHolderInformation.jsx
src/payment/PaymentForm.jsx
src/payment/PaymentForm.messages.jsx
src/payment/PaymentForm.test.jsx
src/payment/__snapshots__/PaymentPage.test.jsx.snap

Add payment form validation

---

package-lock.json
package.json
src/payment/CardDetails.jsx
src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/_style.scss

Add security code field tooltip.

---

src/payment/PaymentPage.test.jsx
src/payment/ProductLineItem.jsx
src/payment/ProductLineItems.jsx
src/payment/__mocks__/loadedBasket.mockStore.js
src/payment/__mocks__/loadedBasketWithNoTotals.mockStore.js
src/payment/data/__mocks__/getBasket.json
src/payment/data/service.js

WIP: change 'name' to 'title' in product details. 
- Also renamed 'img_url/imgURL' to 'image_url/imageURL' for consistencyl. 
- Locally tested with ecommerce @robrap branch ([PR here](https://github.com/edx/ecommerce/pull/2345)). 
*Side note: 
When running tests, came across a warning for certificate types. Created new ticket [ARCH-997](https://openedx.atlassian.net/browse/ARCH-997) ('Verified' vs. 'verified', i18n). 
FYI @edx/arch-squad

rename product name with title

---

src/payment/BasketSummary.jsx
src/payment/PaymentForm.jsx
src/payment/PaymentPage.test.jsx
src/payment/ProductLineItem.jsx
src/payment/ProductLineItems.jsx
src/payment/__mocks__/loadedBasket.mockStore.js
src/payment/__mocks__/loadedBasketWithNoTotals.mockStore.js
src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/_style.scss
src/payment/coupon/data/sagas.js
src/payment/coupon/data/sagas.test.js
src/payment/coupon/data/service.js
src/payment/data/__mocks__/getBasket.json
src/payment/data/service.js

Clean-up include:
- Post and Delete coupon now return the complete basket page (bug on saga with duplicate addCouponSuccess is fixed).
- Discount line no longer displayed when there is no discount . 
- "In your cart" to "In Your Cart"
- Changed section headings to h5 className. 
FYI @edx/arch-squad

UI: Payment Page clean-up

---

src/payment/coupon/CouponForm.jsx
src/payment/coupon/CouponForm.test.jsx
src/payment/coupon/__snapshots__/CouponForm.test.jsx.snap
src/payment/coupon/data/sagas.js
src/payment/coupon/data/sagas.test.js
src/payment/coupon/messages.js
src/payment/data/sagas.js

- Changed `result.coupons === undefined` to `result.coupons.length === 0` to handle when a coupon is removed (coupons returns as an empty array). 
- On CouponForm errors, `already_applied_voucher` should still be referred to 'voucher', not 'coupons'.
- Added back default benefit message to handle coupons with just a code, no value.

fix: coupons empty array

---

src/payment/PaymentForm.jsx
src/payment/PaymentForm.test.jsx

Added `scrollToErrors` where onSubmit of the Payment form, it scrolls to the error message. If there are multiple errors in the form's input fields, scrolls to first error. 
[ARCH-939](https://openedx.atlassian.net/browse/ARCH-939).

refactor: add scroll to error on submit

---

public/index.html
webpack/webpack.common.config.js

The webpack html template will now produce like below if `process.env.OPTIMIZELY_PROJECT_ID` exists. (Companion PR: https://github.com/edx/edx-internal/pull/1010)
```
<!DOCTYPE html>
<html lang="en-us">
<head>
<script src="https://cdn.optimizely.com/js/1234.js"></script>
...
```

feat: add optimizely snippet to top of head

---

package-lock.json
package.json
src/common/serviceUtils.js
src/feedback/AlertList.jsx
src/feedback/AlertMessage.jsx
src/feedback/FallbackErrorMessage.jsx
src/feedback/__mocks__/messagesOfEachType.mockStore.js
src/feedback/__snapshots__/AlertList.test.jsx.snap
src/feedback/data/sagas.js
src/feedback/data/sagas.test.js
src/payment/coupon/data/sagas.test.js
src/payment/data/reducers.js

Log info and errors to New Relic on request errors. Update `handleErrors` to provide a fallback error message rather than bailing.

feat: send errors to NR and add fallback error message

---

.travis.yml
Makefile
package.json

`npm audit` kindly returns a non-zero exit status on any failure.
Note that it also has an `--audit-level` parameter we can choose to use if we want more granular control over what constitutes a failure.  For now it'll fail on any vulnerability.
https://docs.npmjs.com/cli/audit

Fail commit on npm audit vulnerabilities

---

package-lock.json
package.json

We have some country/language packages left over in the app from the days when frontend-i18n was still in the apps.

Removing unused dependencies.

---

package.json
src/index.scss

Saves us about 2k in CSS.  Didn't impact font downloads as we weren't using the FontAwesome font face.  This _does_ remove several extra files from our dist bundle, though they were never being downloaded by the client.  ¯\_(ツ)_/¯
This was for https://openedx.atlassian.net/browse/ARCH-1052

Removing dependency on font-awesome package.

---

build.prod.js

Build config values can't have newlines in them yet so for apple verification config we're using spaces instead. We will replace spaces with newlines when we write out the apple verification file at build time. Companion PR: https://github.com/edx/edx-internal/pull/1028

fix: make newlines from spaces in apple verification config

---

src/payment/CardDetails.jsx
src/payment/CardHolderInformation.jsx
src/payment/CartSummary.jsx
src/payment/OrderSummary.jsx
src/payment/PaymentMethodSelect.jsx
src/payment/ProductLineItem.jsx
src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/_style.scss
src/payment/order-details/OrderDetails.jsx
src/payment/order-details/__snapshots__/OrderDetails.test.jsx.snap

For a11y, added `aria-level` to headings instead of changing the heading size with CSS. 
[ARCH-963](https://openedx.atlassian.net/browse/ARCH-963).

fix: remove heading css, replace with aria-level

---

src/payment/coupon/CouponForm.jsx

The style of FormattedMessage that takes a child function can only handle text arguments to that function, not elements.

fix(prices): fix display of absolute value coupons

---

src/payment/data/service.js

Swap `Number.parseInt(results.orderTotal, 10)` for `Number(results.orderTotal)`
Fixes ARCH-1064

fix: do not lose decimals when parsing numbers

---

src/payment/apple-pay/service.js
src/payment/apple-pay/service.test.js

ARCH-952 Add a flag to the start session request to allow the backend to differentiate between start session requests coming from the legacy page and this new microfrontend

fix: add parameter to apple pay start session

---

src/payment/PaymentPage.jsx
src/payment/data/selectors.js
src/payment/order-summary/CurrencyDisclaimer.jsx
src/payment/order-summary/OrderSummary.jsx

We thought the message about currency conversions being estimates would make more sense closer to the actual prices.
Also italicized the message to match the legacy page.

feature(prices): move localized currency disclaimer closer to prices

---

src/payment/utils/handleBasketApiError.js

Basket data was not properly handled on error. Now if an api call returns an error with data we will populate the app state with it. Partially fixes ARCH-1088.

fix: set basket data on failure

---

src/payment/data/service.js

Inspired by ARCH-1074. If the payment page is directed by the api to redirect to the url it is already on, log an error.

fix: log error on potential redirect loop

---

src/payment/apple-pay/ApplePayButton.jsx

This allows local development on http://localhost in Safari. Without catching errors the page would break.

fix: catch errors when starting an apple pay session

---

.travis.yml
README.rst
codecov.yml

- Makes it so our coverage can only go up or stay the same.
- Removes coveralls - we're not using it for this repo
- Fixes our badges and adds one for codecov (I hope)

Use an ‘auto’ target for patch coverage.

---

public/index.html

The existing basket page loads optimizely after the main body content, near the bottom of the HTML, but still in the body.  Now we do the same.

Move optimizely to bottom of body.

---

src/payment/data/reducers.js

One success buttons will no longer be clickable in the time before the redirect takes hold

fix: keep buttons locks on success

---

src/payment/data/reducers.js
src/payment/data/sagas.js

Aborted transactions no longer lock the page in submitting state if they are aborted.

fix: handling of aborted transactions

---

src/payment/data/reducers.js
src/payment/data/sagas.js
src/payment/data/selectors.js

Fixes doubling clicking errors described in ARCH-1109. Coupon and UpdateQuantity reducers now set isBasketProcessing directly rather than relying on derived state. Leverages the REQUEST action in redux saga routines to toggle isBasketProcessing. Sagas will noop if they are triggered when isBasketProcessing

fix: update is basket processing state

---

src/payment/checkout/payment-form/CardHolderInformation.jsx

Lengths are parity with legacy page. Should fix most problems with CR-1083.
Also changes autocomplete of country from country-name to just country (code).

fix: add maxlength on form inputs

---

src/common/components/FormInput.jsx
src/common/components/FormSelect.jsx
src/payment/__snapshots__/PaymentPage.test.jsx.snap

We were supplying attributes as props to FormInput and FormSelect but not passing them to the rendered html.

fix: passthrough attributes to inputs

---

package-lock.json
package.json
src/common/serviceUtils.js
src/payment/payment-methods/apple-pay/service.js
src/payment/payment-methods/apple-pay/service.test.js
src/payment/payment-methods/cybersource/service.js
src/payment/payment-methods/cybersource/service.test.js
src/payment/payment-methods/paypal/service.js
src/payment/payment-methods/paypal/service.test.js

Swap usage of logAPIErrorResponse with logApiClientError. Message prefixes will now be prepended to error messages in New Relic

fix: upgrade frontend-logging

---

src/payment/data/sagas.js
src/payment/data/sagas.test.js

After a few merges/conflicts we were left in a place where we had a bit too much abstraction in the sagas.  This PR just simplifies that a bit and does a bit of formatting.
Lets us dispatch the fetchBasket.fulfill() action at the right time too.

Folding catchBasketError back into handleFetchBasket for simplicity.

---

src/payment/checkout/payment-form/PaymentForm.test.jsx
src/payment/payment-methods/cybersource/service.js
src/payment/payment-methods/cybersource/service.test.js

Before submitting to CyberSource, strips non-digits (e.g. spaces,
hyphens, etc.) from the credit card number.
ARCH-1148

ARCH-1148: fix: strip non-digits from card number

---

src/payment/checkout/Checkout.jsx
src/payment/checkout/Checkout.test.jsx

This will accompany disabling the flag `enable_apple_pay` on stage and production ecommerce admin, as well as notifying support.
- Support have been notified that this will likely go out Monday, September 9
REV-927

Temporarily disable apple pay

---

src/payment/data/sagas.js
src/payment/data/sagas.test.js

issue: when a payment error happens and the basket page update the discount doesn't get reapplied. this causes the user to get charged the full amount, but then the receipt page shows they got charged the discounted amount
i don't think there is a way to test the fix locally so my suggestion for testing would be to 
merge, deploy to stage, modify local code so that an error on stage is possible, change flags on stage to direct everyone to mfe, make error purchase on stage? no sure if this will work  
if this doesn't work, then just retest successful purchases on stage, then deploy to prod, test payment errors and retest successful purchases and rollback if we find an issue

[WIP] fix discount bug with payment error

---

src/common/utils.js
src/components/App.jsx
src/payment/cart/OrderSummary.jsx
src/payment/checkout/payment-form/PaymentForm.jsx

REV-984
Different types of events will be added later if this does not give us what we need.
Follows the basic idea of https://github.com/edx/edx-mktg/blob/4e3b18a6ad7e2a5b3a048d354f2fef56df0b474d/docroot/sites/all/themes/atedx/scripts/react/pages/privacy_policy/PrivacyPolicy.jsx#L11-#L18

Add some speedcurve events to payment page

---

src/payment/checkout/payment-form/PaymentForm.jsx

The payment form finishes loading at essentially the same time the
order summary mounts, so that doesn't tell us much about the timing
differences between the right and left sides of the page. Adding this
will give us a bit more info about when the payment form first becomes
visible.
**Payment form mount:**

Add speedcurve event for when PaymentForm mounts

---

src/payment/AlertCodeMessages.test.jsx
src/payment/PaymentPage.test.jsx
src/payment/cart/Cart.test.jsx
src/payment/cart/CouponForm.test.jsx
src/payment/cart/LocalizedPrice.test.jsx
src/payment/cart/Offers.test.jsx
src/payment/cart/__snapshots__/LocalizedPrice.test.jsx.snap
src/payment/data/__snapshots__/redux.test.js.snap
src/payment/data/reducers.js
src/payment/data/redux.test.js
src/payment/data/selectors.js

We need to wait long enough for the app to know the name of the cookie via CURRENCY_COOKIE_NAME, which is attached to App.config during the startup sequence.  By reading the cookie during a selector instead of at load-time in the reducers file, we sufficiently delay that it picks up the real cookie value.
This means the currency reducer is no longer needed, as the selector reads it from the cookie itself.  That necessitates cleaning up a bunch of reducer/state related setup in our tests.

fix: implement currency cookie detection as selector

---

public/index.html

This makes two changes that should improve optimizely performance
1. adds preload tag to the optimizely snippet
2. changes optimizely snippet to load from a cloudflare worker (that should be caching our js at https://payment.edx.org/optimizelyjs/1743970571.js)
Hoping to deploy this and then hopefully see a performance improvement when inspecting optimizely in speedcurve

preload optimizely snippet from cloudflare worker

---

src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/checkout/Checkout.jsx
src/payment/checkout/payment-form/CardHolderInformation.jsx
src/payment/checkout/payment-form/PaymentForm.jsx
src/payment/index.scss

[REV-937](https://openedx.atlassian.net/browse/REV-937).
Enable form fields to be editable while basket is loading.
Disable form fields onSubmit of form. 
Bulk Purchase - quantity updating disable submit button. 
*Note: updated CSS of checkbox, on zoom in Chrome the size changes to an abnormally large size.

Update form to be editable on load

---

package-lock.json
public/index.html

i have a call with optimizely on thursday to check my implementation of this so i'd like to add it back, at least temporarily
the jump last time this happened that stayed after reverting was weird, so hopefully this also shows whether it causes a jump in visually complete again
(if it does, i think this might be what was happening)
1. https://cdn.optimizely.com/js/1743970571.js gets loaded on login page (which is being excluded from the speedcurve performance with logData 0)
2. that url gets cached and doesn't add a request to webpagetest
3. when i changed the url on frontend-app-payment only, the url could no longer be retrieved from the browser cache

Revert "Revert "preload optimizely snippet from cloudflare worker""

---

package-lock.json
src/index.jsx

Related to ARCH-1304.
Some users payment submissions fail with a jwt expiration error on the server. It's unclear why the this client application doesn't see the jwt as expire too. We will investigate. Temporarily this fix will refresh the jwt cookie before every post request on the page to ensure the jwt cookie is as fresh as it could be. We will see if this eliminates the errors.
Also, this includes upgrades to satisfy npm audit.

Force refresh the jwt cookie before all post requests

---

public/index.html

i've shown that switching the snippet to request from payment.edx.org instead of cdn.optimizely.com set the dns, connect, and ssl portions of the request to 0ms
however, this was not ideal because payment.edx.org will not be in the browser cache and so might actually perform worse on the whole
if using edx.org will create the same benefit for the dns/connect/ssl portions of the request, then this would be the ideal scenario for both when the content is cached and when it is not cached

switch optimizely snippet

---

package.json
public/REV1074/test.html
webpack.prod.config.js

to the dist folder where they will be accessible through a url
This is necessary because the html for those pages needs to be in the dist folder to be publicly accessible
https://openedx.atlassian.net/browse/REV-1112
@edx/revenue-squad

[REV-1074] Copy static checkout pages 

---

.travis.yml
package-lock.json
package.json

Upon `npm audit` there are certain package vulnerabilities that do not have a quick fix at the moment - this should not stop us from having commits and merging PRs. 
By utilizing [audit-ci](https://www.npmjs.com/package/audit-ci), we can whitelist these specific packages. Now the pre-commit hooks will run the whitelisted command instead of `npm audit`.
- [minimist](https://www.npmjs.com/advisories/1179) (low). 
- [acorn](https://npmjs.com/advisories/1488) (moderate): current version of es-check accepts affected acorn version 6.0.4, latest version also accepts affected acorn version 6.1.1. 
- [decompress](https://npmjs.com/advisories/1217) (high): no fix is currently available.

Add whitelist with certain npm packages with vulnerabilities

---

src/index.jsx
src/payment/cart/OrderSummary.jsx
src/payment/checkout/Checkout.jsx
src/payment/index.js

Added some test events using the same mechanism we intend to use for REV-1074 static checkout pages
Note that I wrote the `sendRev1074Event` with an eye to being able to just drop it into the static pages when we add events there.

Added events using the same mechanism as static checkout pages

---

src/payment/AlertCodeMessages.jsx
src/payment/__snapshots__/AlertCodeMessages.test.jsx.snap

Removed support link from payment declined error message and updated the wording to direct learners to their payment provider or bank.
[PROD-1417](https://openedx.atlassian.net/browse/PROD-1417)

Update payment declined message.

---

README.rst
src/payment/payment-methods/cybersource/service.js
src/payment/payment-methods/cybersource/service.test.js

[REV-1125](https://openedx.atlassian.net/browse/REV-1125). 
- Removing the call to the SDN search endpoint (api/v2/sdn/search/) because we've added the SDN check to the Cybersource api submit (payment/cybersource/api-submit), so this will remove the duplicated SDN check. 
- Removing related tests.

Remove call to SDN search endpoint and associated tests 

---

src/payment/PaymentPage.jsx

Fetching the capture key eventually triggers the timer for the messages about completing the purchase before the key has to be refreshed, these messages currently get displayed in the old flow with the non-microform fields.

Only fetch the capture key if the microform is enabled

---

src/payment/PaymentPage.jsx
src/payment/data/sagas.js

Only fetching the capture key if the microform is enabled sometimes failed to do the fetch; moving the check to only affect the timeout and messages.

Only start capture key timeout if the microform is enabled

---

src/payment/checkout/payment-form/flex-microform/CreditCardNumberField.jsx
src/payment/payment-methods/cybersource/service.js

Validate the card type and show the appropriate error; still using the old list of card types
Creating a new list of card types for this validation to use with the full compliment Cybersource will process for us will be done separately as part of cleanup, if we choose to do that.

Validate the card type and show the appropriate error

---

src/payment/checkout/payment-form/PaymentForm.old.test.jsx
src/payment/checkout/payment-form/utils/credit-card.js
src/payment/checkout/payment-form/utils/credit-card.test.js

Note: a local test with the Diners test card did not work, I've reached out to ask if it is expected to work in the test environment
UPDATE: apparently those card types are not enabled in our testing profile, looking into updating our profiles now
UPDATE 2: I did not see how to update our test profile, but a test with the REST API succeeded without changing anything; since we are moving off SOP hopefully it will work in prod, but I updated our production SOP profile just in case.

REV-1592 Enable Diners Club and JCB card types

---

package-lock.json
package.json
src/index.scss
src/payment/__snapshots__/PaymentPage.test.jsx.snap
src/payment/cart/CouponForm.jsx
src/payment/cart/__snapshots__/Cart.test.jsx.snap
src/payment/cart/__snapshots__/CouponForm.test.jsx.snap
src/payment/checkout/payment-form/CardHolderInformation.jsx
src/payment/checkout/payment-form/PaymentForm.jsx
src/payment/checkout/payment-form/StateProvinceFormInput.jsx
src/payment/index.scss

[REV-1604](https://openedx.atlassian.net/browse/REV-1604). 
Retheme using @edx/brand.
Pls note: in order to see this branch locally, you need to run `npm install --save @edx/brand@npm:@edx/brand-edx.org` 
More details on UX's feedback on the ticket, screenshots have been approved with the below changes:
1) Loading state skeleton updated to reflect no rounded borders for both form items and submit button. 
2) Coupon button changed to `outline-primary` and field width changed to align with the course title. 
Mobile:
3) Firefox displayed an issue with a double dropdown in the selector field for country and state. 
Fixed:

Update rebranding styles, retheme with @edx/brand

---

package-lock.json
package.json

[REV-2084](https://openedx.atlassian.net/browse/REV-2084). 
Upgrading the below packages that have a security vulnerability:
- immer 
- yargs-parser (dependency)
Upgrading the below that is out of date:
- es-check
NOTE: `dev: true` and the version with and without `^` where removed/added automatically with `npm install package_name` or `npm install --save package_name`

Upgrade packages with security vulnerabilities 

---

README.rst

Recommend `npm ci` over `npm install` to minimize package_lock changes and match CI and prod builds

Update README to recommend `npm ci`

---

.github/PULL_REQUEST_TEMPLATE.md

Add an expanded PR template that also directs edX engineers to instructions for deploying their changes

REV-2099: Add an expanded PR template

---

openedx.yaml

Also remove two obsolete keys.
This repo is part of the Open edX installation, but wasn't marked as such.  Now it is.

build: include this repo in Open edX releases

---

audit-ci.json

Our pre-commit hook had been failing because of our previous settings in audit-ci.json: 
- object-path was there (which we don't depend on anymore)
- other vulnerabilities: 565, 1675, 1676, 1677, 1693, 1745, 1747 (which we can add directly)
I've updated audit-ci.json accordingly, and now the pre-commit hook no longer fails, and the build checks no longer fail 
Ben has checked these vulnerabilities, and the one that's a prod dependency is sanitize-html <2.3.1 (id 1676), which is used by Paragon- ticket filed to address this here: 
https://openedx.atlassian.net/browse/REV-2249

Clean up audit-ci.json

---

src/payment/checkout/payment-form/utils/countryStatesMap.js

In [REV-2217](https://openedx.atlassian.net/browse/REV-2217) added a state drop-down menu for India. I just noticed a missing space in West Bengal- fixing it in this PR

fix: add missing space in state display name

---

src/payment/checkout/payment-form/PaymentForm.jsx
src/payment/checkout/payment-form/PaymentForm.messages.jsx

There is an issue with the SDN fallback check that is locking accounts if the name contains no ascii characters.
Added a form validation check that the name fields contain ascii letters as a short-term mitigation for [[REV-2491] Explosion in SDN hits for users with Chinese character names - JIRA](https://openedx.atlassian.net/browse/REV-2491)
It is OK for this to be a client-side check; if anyone circumvents it, they just get their account locked by the bug.
This can be tested by attempting to purchase a course and using only non-ascii letters in the name fields, for example `中国人`, adding any ascii letters will allow the fields to validate.

temp!: temporarily required ascii characters in name fields

---

Makefile
package-lock.json
package.json
src/payment/PaymentPage.jsx
src/payment/PaymentPage.messages.jsx

[REV-2643](https://openedx.atlassian.net/browse/REV-2643).
Transifex is deprecating its version 2, we need to update to v3 so our scripts don't fail when the change happens on April 7th, 2022.
**This PR:**
- Add our maintained version `@edx/reactifex`
- Update Makefile commands for new v3 transifex API
- Edit one description in the message file to test push translation job

chore: Update transifex api from v2 to v3

---

CODEOWNERS

Currently, our CODEOWNERS file may not be working because the group `@edx/revenue-squad` no longer exists.
This PR corrects `@edx/revenue-squad` to `@openedx/revenue-squad`.
It also adds the CODEOWNERS file itself as a file requiring approval from @openedx/revenue-squad.
* Jira: [REV-2707](https://openedx.atlassian.net/browse/REV-2707)

fix: convert CODEOWNERS to @openedx and add self-check

---

webpack.prod.config.js

This reverts commit ca0ff1140cc18b98abba6809f6e5abaf4d39d439.
As it turns out, this commit is the actual culprit. It is double-loading <script>s, which triggers a bug further downstream in our project. However, this still introduces a bug, so backing out this code.
You can see the issue on stage in the screenshot below. Note the <script> tags with the same source.
* Jira: [REV-2674](https://2u-internal.atlassian.net/browse/REV-2674)
* Local
* Stage
* Prod

Revert "Revert "Revert "fix: Edit HtmlWebpackPlugin for New Relic snippet from frontend-build (#593)" (#594)

---

.github/workflows/lockfileversion-check.yml

- This PR replaces https://github.com/openedx/frontend-app-payment/pull/600 to add the package-lock version file check. It has been blocked due to the failures occurring on master so can be merged now.

build: Add package-lock file version check

---

.github/workflows/ci.yml

Now that we are pushing the Project Zebra code to master, we no longer need the CI to run on that branch.
Partial revert of 95085161fa9a1f84d1e109505baf1a0fb08ed720
* Jira: [REV-3146](https://2u-internal.atlassian.net/browse/REV-3146) Cleanup: Remove project-zebra branch from CI

build: retire branch project-zebra CI

---

Makefile

- `Transifex` latest version requires `-t` parameter with the `tx pull` command to work properly.

fix: fix transifex pull translations command

---

README.rst
docs/decisions/0005-stripe-custom-actions.rst

Add an ADR describing why we chose to use Stripe Custom Actions instead of the regular Stripe Payments flow.
The sequence diagram is being made in [REV-3229](https://2u-internal.atlassian.net/browse/REV-3229).
* Jira: [REV-3150](https://2u-internal.atlassian.net/browse/REV-3150) Update the decisions docs with Stripe work for payment MFE and ecommerce.

docs: add ADR 5 for Stripe Custom Actions & update README.rst

---

audit-ci.json

Unblocking PON-82 for Ponderosa Squad to avoid duplicate work on both `master` and `ponderosa-master` branches.
https://github.com/advisories/GHSA-hc6q-2mpp-qw7j
Upgrading `webpack 5` would install `frontend-build` at v6.1.1 which is a breaking change.

chore: Update audit-ci with vulnerability w breaking change

---

audit-ci.json

[PON-179](https://2u-internal.atlassian.net/browse/PON-179).
Unblocking Ponderosa folks on making commits on `ponderosa-master` branch.
Added: https://github.com/advisories/GHSA-f9xv-q969-pqx4
Otherwise, we would need to upgrade `yaml` to v2 from v1, major change which according to NPM it's a breaking change.

chore: Add yaml vulnerability to allowlist to unblock commits

---

audit-ci.json

Translations jobs in Jenkins were failing due to the removal of some GitHub groups by Axim (https://tools-edx-jenkins.edx.org/job/translations/job/frontend-app-payment-pull_translations/240/console).
There was a fix on their end, but the translation PR failed https://github.com/openedx/frontend-app-payment/pull/766 due to a security vulnerability on `semver` versions < 7.5.2 which is dependency in various packages we use - 
https://github.com/advisories/GHSA-c2qf-rxjj-qqgw

fix: Update allowlist to unblock translations

---

public/index.html

This PR reverted the change for adding a Content Security Policy meta tag in the index.html. We are going to update the `terraform` CSP headers for payment MFE.

revert: removed the CSP meta tag

---

docs/how_tos/feedback.rst

Add HOWTO for feedback module.
* Jira: [THES-228](https://2u-internal.atlassian.net/browse/THES-228)

docs: add feedback.rst HOWTO

---

audit-ci.json

[REV-3662](https://2u-internal.atlassian.net/browse/REV-3662).
Security advisory for `adobe/css-tools`, version 4.3.0 and earlier are affected. This is a dependency for `@testing-library/jest-dom`, but the latest version has `adobe/css-tools` at version 4.3.0.
Adding to allowlist to unblock any commits for now.
https://github.com/advisories/GHSA-hpx4-r86g-5jrg

fix: Add security advisory to allowlist for adobe/css-tools

---

Makefile
audit-ci.json
package-lock.json
package.json

Backport https://github.com/openedx/frontend-app-payment/pull/813
Without this change, building the payment MFE fails during `npm ci` with the following error:
```
> [payment-common 3/5] RUN --mount=type=cache,target=/root/.npm,sharing=shared npm clean-install --no-audit --no-fund --registry=https://registry.npmjs.org/:                                                     
7.939 npm ERR! code EUSAGE                                                                                                                                                                                         
7.950 npm ERR! …
```

feat: babel-plugin-react-intl to babel-plugin-formatjs migration (#813)
